---
name: "Frenck's Home Assistant App Linter"
description: 🚀 Frenck's GitHub Action for linting Home Assistant Apps.
author: frenck

branding:
  color: red
  icon: thumbs-up

inputs:
  path:
    description: Path to the app configuration (where config.json is)
    required: true
  community:
    description: Enable Home Assistant Community Apps mode
    default: "false"
    required: false

runs:
  using: "docker"
  image: "src/Dockerfile"
